# Generated by Django 4.2 on 2023-04-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
