# Generated by Django 4.1.7 on 2023-03-13 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0004_contact_us_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
