# Generated by Django 4.1.7 on 2023-03-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0005_contact_us_user_alter_contact_us_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='email',
        ),
    ]
