# Generated by Django 4.1.7 on 2023-03-17 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0007_user_email_verified_verificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='promo_code_personal',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basegpt.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_by',
            field=models.ManyToManyField(through='basegpt.PromoCodeUsage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basegpt.promocode'),
        ),
    ]
