# Generated by Django 4.1.7 on 2023-03-17 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0008_promocode_user_promo_code_personal_promocodeusage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promo_code_personal',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
