# Generated by Django 4.1.7 on 2023-03-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0009_alter_user_promo_code_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='promo_code_personal',
        ),
    ]
