# Generated by Django 4.1.7 on 2023-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0012_alter_user_promo_code_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='promo_code_personal',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
