# Generated by Django 4.1.7 on 2023-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0016_user_code_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.FloatField(default=1),
        ),
    ]
