# Generated by Django 4.1.7 on 2023-03-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0017_alter_promocode_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
