# Generated by Django 4.1.7 on 2023-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0019_alter_promocode_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquetext',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
