# Generated by Django 4.1.7 on 2023-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0020_uniquetext_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
