# Generated by Django 4.1.7 on 2023-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0022_order_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquetext',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
