# Generated by Django 4.1.7 on 2023-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0023_uniquetext_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
