# Generated by Django 4.1.7 on 2023-03-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0025_examtext_delete_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtext',
            old_name='response',
            new_name='response_text',
        ),
    ]
