# Generated by Django 4.1.7 on 2023-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0026_rename_response_examtext_response_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtext',
            old_name='request',
            new_name='rawtext',
        ),
    ]
