# Generated by Django 4.1.7 on 2023-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0027_rename_request_examtext_rawtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
