# Generated by Django 4.1.7 on 2023-04-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basegpt', '0028_order_idea_alter_order_type_alter_order_type2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtext',
            old_name='response_text',
            new_name='responsetext',
        ),
    ]
