# Generated by Django 4.2 on 2023-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_temp',
            field=models.FloatField(default=1),
        ),
    ]
