# Generated by Django 4.2 on 2023-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
