# Generated by Django 4.2 on 2023-08-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_user_admin_alter_user_custom_temp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscriptions',
        ),
    ]
