# Generated by Django 4.2 on 2023-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_analyticsperiods_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message',
            field=models.DateField(null=True),
        ),
    ]
