# Generated by Django 4.2 on 2023-09-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_user_email_alter_user_expired_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expired_date',
            new_name='reminder_date',
        ),
    ]
