# Generated by Django 4.2 on 2023-09-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_rename_expired_date_user_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('input_tokens', models.IntegerField(default=0, null=True)),
                ('output_tokens', models.IntegerField(default=0, null=True)),
                ('total_user_tokens', models.IntegerField(default=0, null=True)),
                ('count_sum', models.IntegerField(default=0, null=True)),
                ('input_sum', models.IntegerField(default=0, null=True)),
                ('output_sum', models.IntegerField(default=0, null=True)),
                ('total_sum', models.IntegerField(default=0, null=True)),
                ('total_tokens', models.IntegerField(default=0, null=True)),
                ('messages', models.IntegerField(default=0, null=True)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subscriptions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('id',), name='sessions_pkey'),
        ),
    ]
