# Generated by Django 4.2 on 2023-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_user_active_days_user_sold_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateField(),
        ),
    ]
