# Generated by Django 4.2 on 2023-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
