# Generated by Django 4.2 on 2023-09-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_session_input_tokens_before_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='total_tokens',
            new_name='input_price',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user_id',
        ),
        migrations.AddField(
            model_name='session',
            name='output_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_input',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_output',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Subscriptions_statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sessions', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='sub_stat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.subscriptions_statistics'),
            preserve_default=False,
        ),
    ]
