# Generated by Django 4.2 on 2023-09-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_rename_total_tokens_session_input_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sub_stat_id',
            new_name='sub_stat',
        ),
    ]
