# Generated by Django 4.2 on 2023-09-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_rename_sub_stat_id_session_sub_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='expired_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='expired_tokens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='role_edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='temp_edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='subscriptions_statistics',
            constraint=models.UniqueConstraint(fields=('id',), name='subscriptions_statistics_pkey'),
        ),
    ]
