# Generated by Django 4.2 on 2023-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_subscriptions_statistics_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions_statistics',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
