# Generated by Django 4.2 on 2023-09-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_subscriptions_statistics_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='expired_tokens',
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='expired_reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
