# Generated by Django 4.2 on 2023-09-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_remove_subscriptions_statistics_expired_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='total_tokens',
        ),
        migrations.RemoveField(
            model_name='session',
            name='input_price',
        ),
        migrations.RemoveField(
            model_name='session',
            name='output_price',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_input',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_output',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_sum',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_user_tokens',
        ),
    ]
