# Generated by Django 4.2 on 2023-09-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_remove_analyticsformonth_total_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='active',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='expired_time',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='expired_tokens',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='income',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='role_edited',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='temp_edited',
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='sessions',
        ),
    ]
