# Generated by Django 4.2 on 2023-09-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_remove_analyticsformonth_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='count_sum',
        ),
        migrations.RemoveField(
            model_name='session',
            name='input_sum',
        ),
        migrations.RemoveField(
            model_name='session',
            name='output_sum',
        ),
    ]
