# Generated by Django 4.2 on 2023-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_remove_session_count_sum_remove_session_input_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
