# Generated by Django 4.2 on 2023-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_analyticsforday_active_non_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='input_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='messages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='output_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
