# Generated by Django 4.2 on 2023-10-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_subscriptions_statistics_input_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sold',
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='active_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
