# Generated by Django 4.2 on 2023-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_remove_user_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsforday',
            name='costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsforday',
            name='income',
            field=models.FloatField(default=0),
        ),
    ]
