# Generated by Django 4.2 on 2023-10-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_analyticsforday_costs_analyticsforday_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics_by_day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('input_tokens', models.IntegerField(default=0, null=True)),
                ('output_tokens', models.IntegerField(default=0, null=True)),
                ('messages', models.IntegerField(default=0, null=True)),
                ('costs', models.FloatField(default=0, null=True)),
                ('income', models.FloatField(default=0, null=True)),
                ('sub_stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.subscriptions_statistics')),
            ],
        ),
        migrations.RemoveField(
            model_name='analyticsformonth',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='analyticsperiods',
            name='sub_type',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sub_stat',
        ),
        migrations.DeleteModel(
            name='AnalyticsForMonth',
        ),
        migrations.DeleteModel(
            name='AnalyticsPeriods',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddConstraint(
            model_name='statistics_by_day',
            constraint=models.UniqueConstraint(fields=('id',), name='statistics_by_day_pkey'),
        ),
    ]
