# Generated by Django 4.2 on 2023-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_statistics_by_day_remove_analyticsformonth_sub_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics_by_day',
            name='income',
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='income',
            field=models.FloatField(default=0, null=True),
        ),
    ]
