# Generated by Django 4.2 on 2023-10-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_subscriptions_multimodal_user_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='multimodal',
            new_name='multimodel',
        ),
    ]
