# Generated by Django 4.2 on 2023-10-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_subscriptions_multi_k'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_days',
        ),
        migrations.AddField(
            model_name='user',
            name='campaign_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_campaign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
