# Generated by Django 4.2 on 2023-10-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_remove_user_active_days_user_campaign_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='utm_term',
        ),
        migrations.AddField(
            model_name='user',
            name='phrase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
