# Generated by Django 4.2 on 2023-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_remove_user_campaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
