# Generated by Django 4.2 on 2023-10-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_user_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='source',
        ),
        migrations.RemoveField(
            model_name='user',
            name='utm_medium',
        ),
    ]
