# Generated by Django 4.2 on 2023-10-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_remove_user_source_remove_user_utm_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region_id',
        ),
    ]
