# Generated by Django 4.2 on 2023-10-29 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0043_alter_user_ad_id_alter_user_phrase_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('work_cost', models.FloatField(default=0)),
                ('personal_cost', models.FloatField(default=0)),
                ('type_now', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='subscriptions_statistics',
            name='output_tokens',
        ),
        migrations.DeleteModel(
            name='AnalyticsForDay',
        ),
    ]
