# Generated by Django 4.2 on 2023-11-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_adminstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='photo_send',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo-1106', max_length=50, null=True),
        ),
    ]
