# Generated by Django 4.2 on 2023-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_subscriptions_statistics_photo_send_alter_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='image_generated',
            field=models.IntegerField(default=0),
        ),
    ]
