# Generated by Django 4.2 on 2023-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0046_subscriptions_statistics_image_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='gen_im',
            field=models.BooleanField(default=False),
        ),
    ]
