# Generated by Django 4.2 on 2023-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_rename_phrase_id_user_client_id_user_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
        migrations.AddField(
            model_name='user',
            name='client_id_metrika',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
