# Generated by Django 4.2 on 2023-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0049_remove_user_client_id_user_client_id_metrika'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='cost',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions_statistics',
            name='order_id_payment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
