# Generated by Django 4.2 on 2023-11-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0050_subscriptions_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_type',
        ),
    ]
