# Generated by Django 4.2 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0051_remove_user_ad_id_remove_user_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_channel_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
