# Generated by Django 4.2 on 2024-03-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0052_user_tg_channel_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poll_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
