# Generated by Django 4.2 on 2024-05-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0054_alter_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions_statistics_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0, null=True)),
                ('output_tokens', models.IntegerField(default=0, null=True)),
                ('messages', models.IntegerField(default=0, null=True)),
                ('sub_stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.subscriptions_statistics')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptions_statistics_model',
            constraint=models.UniqueConstraint(fields=('id',), name='subscriptions_statistics_model_pkey'),
        ),
    ]
