# Generated by Django 4.2 on 2024-08-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0055_subscriptions_statistics_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name_user', models.CharField(max_length=100, null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('max_tokens', models.IntegerField(default=4096, null=True)),
                ('model_k', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.CharField(default='gpt-4-mini', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Subscriptions_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.models')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subscriptions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptions_models',
            constraint=models.UniqueConstraint(fields=('sub', 'model'), name='subscriptions_models_pkey'),
        ),
    ]
