# Generated by Django 4.2 on 2024-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0056_models_alter_user_model_subscriptions_models_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.models'),
        ),
    ]
