# Generated by Django 4.2 on 2024-09-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0062_offline_conversions_settings_offline_conversions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offline_conversions_settings',
            old_name='week_count',
            new_name='day_count',
        ),
        migrations.RenameField(
            model_name='offline_conversions_settings',
            old_name='week_max',
            new_name='day_max',
        ),
        migrations.AddField(
            model_name='offline_conversions_settings',
            name='day_last_reset',
            field=models.DateField(null=True),
        ),
    ]
